# Generated by Django 3.1.1 on 2021-01-05 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='quiz_images'),
        ),
    ]
