# Generated by Django 3.1.1 on 2021-01-06 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_auto_20210106_0135'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizmodel',
            name='correct_option',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
