# Generated by Django 3.1.1 on 2021-01-06 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_quizmodel_correct_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizmodel',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='quizmodel',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
    ]
