# Generated by Django 3.1.1 on 2021-01-25 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_auto_20210106_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizmodel',
            name='poller',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='quizmodel',
            name='question',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='quizmodel',
            name='quiz_title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
