# Generated by Django 3.1.1 on 2021-01-25 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_auto_20210125_1919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizmodel',
            name='correct_option_1',
        ),
        migrations.RemoveField(
            model_name='quizmodel',
            name='correct_option_2',
        ),
        migrations.RemoveField(
            model_name='quizmodel',
            name='correct_option_3',
        ),
        migrations.RemoveField(
            model_name='quizmodel',
            name='correct_option_4',
        ),
        migrations.RemoveField(
            model_name='quizmodel',
            name='correct_option_5',
        ),
        migrations.RemoveField(
            model_name='quizmodel',
            name='correct_option_6',
        ),
    ]
