# Generated by Django 3.1.1 on 2021-01-25 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0013_auto_20210126_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizmodel',
            name='poller',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
