# Generated by Django 3.1.1 on 2021-07-21 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0014_auto_20210126_0229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizmodel',
            name='correct_option',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
