# Generated by Django 3.1.1 on 2021-01-04 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PollModel',
            fields=[
                ('poll_id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.TextField(max_length=100)),
                ('user_id', models.CharField(max_length=10)),
                ('state_option_four', models.BooleanField(blank=True, default=True)),
                ('option_one', models.CharField(max_length=30)),
                ('option_two', models.CharField(max_length=30)),
                ('option_three', models.CharField(max_length=30)),
                ('option_one_count', models.PositiveIntegerField(default=0)),
                ('option_two_count', models.PositiveIntegerField(default=0)),
                ('option_three_count', models.PositiveIntegerField(default=0)),
                ('option_four_nota_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'poll_table_temp',
            },
        ),
    ]
